# Generated by Django 4.0.4 on 2022-05-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropessoa',
            name='cpf',
            field=models.DecimalField(decimal_places=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='cadastropessoa',
            name='data_nacimento',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cadastropessoa',
            name='telefone',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
