# Generated by Django 4.0.4 on 2022-05-28 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastrarPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cpf', models.IntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('telefone', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CadastrarAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(choices=[('IDServiço', 'IDServiço'), ('Orientação para MEI', 'Orientação para MEI'), ('Consulta prévia de Localização', 'Consulta prévia de Localização'), ('Registro, alteração e baixa do MEI', 'Registro, alteração e baixa do MEI'), ('Emissão de boletos', 'Emissão de boletos'), ('Orientação sobre renovação de alvará', 'Orientação sobre renovação de alvará'), ('Orientação para emissão de NF', 'Orientação para emissão de NF')], max_length=50)),
                ('data', models.DateField()),
                ('atendente', models.CharField(choices=[('Arande', 'Arande'), ('Carlos', 'Carlos'), ('Carolina', 'Carolina'), ('Larissa', 'Larissa'), ('Micael', 'Micael'), ('Rafael', 'Rafael'), ('Rodrigo', 'Rodrigo')], max_length=20)),
                ('cadastrarpessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cadastrarpessoa', verbose_name='CPF')),
            ],
        ),
    ]
