# Generated by Django 4.0.4 on 2022-06-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrarpessoa',
            name='data',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
