# Generated by Django 4.0.4 on 2022-06-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cadastraratendimento_cadastrarpessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastraratendimento',
            name='servico',
            field=models.CharField(choices=[('Orientação para MEI', 'Orientação para MEI'), ('Consulta prévia de Localização', 'Consulta prévia de Localização'), ('Registro, alteração e baixa do MEI', 'Registro, alteração e baixa do MEI'), ('Emissão de boletos', 'Emissão de boletos'), ('Orientação sobre renovação de alvará', 'Orientação sobre renovação de alvará'), ('Orientação para emissão de NF', 'Orientação para emissão de NF')], max_length=50),
        ),
    ]
