# Generated by Django 4.0.4 on 2022-06-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cadastrarpessoa_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrarpessoa',
            name='cep',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastrarpessoa',
            name='telefone',
            field=models.BigIntegerField(),
        ),
    ]
